### ISSUE TITLE
Issues when up to production

### ISSUE THREAD

**Issue by KosorlYoeng** [BRACKETS-by-TRIAD/craftable-pro-docs#100]
issues "Why I up the project to production it display blank white screen when i access to /admin/login"

**Comment by strstensky** [comment]
Did you run `npm run craftable-pro:build` after depolyment?

**Comment by KosorlYoeng** [comment]
Yes, already

**Comment by strstensky** [comment]
And it ran without any problems? A white page usually indicates that the frontend hasn’t been compiled. Do you see any errors in the console?

**Comment by KosorlYoeng** [comment]
I don't see all errors in the console

**Comment by KosorlYoeng** [comment]
https://uniclubzone.paragoniu.app/

Here is my website, You can check it

**Comment by strstensky** [comment]
I checked your website and I saw the PHP error unrelated to Craftable PRO:
```
file_put_contents(/var/www/html/club/storage/framework/views/99eb1ac00707a17563604ccbe43bbb1a.php): Failed to open stream: Permission denied
```

It looks like you need to change permissions to the storage folder, see this StackOverflow thread: https://stackoverflow.com/a/54070254/23195683 .

**Comment by KosorlYoeng** [comment]
I fix already, U can check it again ?

**Comment by strstensky** [comment]
Please try to run `npm run craftable-pro:build` on your server and paste the output here so that I can check for any errors.

**Comment by KosorlYoeng** [comment]
I try a long time but it still blank white screen

**Comment by strstensky** [comment]
I understand. Could you please paste your command-line interface output here after running the command? You can see the example of the output in our tutorial video at the 3:50 timestamp: https://youtu.be/IU3zBf_ioyk?si=HuHj7hAFsEwhBYh2&t=230.

**Comment by KosorlYoeng** [comment]
can you clarify this?

**Comment by strstensky** [comment]
After you run the command `npm run craftable-pro:build`, you should see some output in your command line interface, something like this:
![image](https://github.com/user-attachments/assets/b1027e20-3440-4187-afb5-92ef67f84a56)

Can you copy & paste the output here or at least send a screenshot?

**Comment by KosorlYoeng** [comment]
![screenshot](https://github.com/user-attachments/assets/9ca784e6-1e15-4ac4-ac81-6771e580c8d4)

**Comment by strstensky** [comment]
That seems fine. Would you mind sharing repository access with me so I can check the code?

**Comment by KosorlYoeng** [comment]
Here 
https://github.com/vividnestor/uniclubzone.git

**Comment by strstensky** [comment]
I checked your repository, and in the file resources/views/craftable-pro.blade.php, you are missing this line after `@routes`:
```
@vite(['resources/js/craftable-pro/index.ts', 'resources/css/craftable-pro.css'])
```
I also updated the packages using `npm update`. After that, I was able to see the admin panel correctly.

**Comment by KosorlYoeng** [comment]
It working thank you so much.
