### ISSUE TITLE
MultiSelect search-change

### ISSUE THREAD

**Issue by cengizbarul** [BRACKETS-by-TRIAD/craftable-pro-docs#101]
Hello, I need to listen to the text with search-change in multi-select and get data accordingly, how can I do this?

And if I edit the multiselect, won't this be lost when the package is updated, can you add the search-change feature?

**Comment by strstensky** [comment]
Hello, our multiselect uses @vueform/multiselect under the hood. We’ve released a new version of Craftable PRO (v2.0.4), where we enhanced the multiselect to fully support the functionality you need by passing the necessary props to the core Multiselect package. You can now edit Multiselect directly in the Form.vue and use async options. See an example in the documentation:
https://www.npmjs.com/package/@vueform/multiselect#tags-with-async-options.

You can also use the @search-change event. For more details, see:
https://www.npmjs.com/package/@vueform/multiselect#events.

You won’t need to edit the Multiselect component itself, only its props, so no need to worry about package updates. This will have no impact on your generated CRUD.

**Comment by cengizbarul** [comment]
Yes, but it doesn't work very well, this way I can work with inertia, could you please add it?

**Comment by strstensky** [comment]
There shouldn't be any issues using it with Inertia. Please share your code here, and I'll take a look at it.

**Comment by cengizbarul** [comment]
<template>
  <PageContent>
    <div class="mx-auto max-w-3xl 2xl:max-w-4xl">
      <Card>
        <div class="space-y-4">
          <Multiselect
            v-model="form.page_id"
            name="page_id"
            :label="$t('craftable-pro', 'CmsPage')"
            :options="cmsPageOptions"
            mode="single"
          />

          <TextInput
            v-model="form.title"
            name="title"
            :label="$t('craftable-pro', 'Title')"
          />

          <Multiselect
            v-model="form.games"
            name="multiselect3"
            mode="multiple"
            :options="
              async function (query, select$) {
                return await testFetch(query); // check JS block in JSFiddle for implementation
              }
            "
            :createOption="false"
            :searchable="true"
            :label="$t('craftable-pro', 'Games')"
            :resolveOnLoad="true"
          />

          <TextInput
            v-model="form.order"
            name="order"
            :label="$t('craftable-pro', 'Order')"
          />

          <Checkbox
            v-model="form.status"
            name="status"
            :label="$t('craftable-pro', 'Status')"
          />
        </div>
      </Card>
    </div>
  </PageContent>
</template>

<script setup lang="ts">
import { ref } from "vue";
import {
  Card,
  TextInput,
  Wysiwyg,
  TextArea,
  PageContent,
  DatePicker,
  Checkbox,
  Dropzone,
  ImageUpload,
  Multiselect,
  CardLocaleSwitcher,
} from "craftable-pro/Components";
import { InertiaForm } from "craftable-pro/types";
import type { GameCategoryForm } from "./types";
import { router } from "@inertiajs/vue3";
import debounce from "lodash/debounce";

const search = ref("");
const gameName = ref("");
const game_lists = ref([]);

const testFetch = async (query: string) => {
    console.log("query", query);
};


const testSearch = (query: string) => {
  console.log("query");
  console.log(query);
  if (query.length < 3) {
    return;
  }
  gameName.value = query;
  searchGames(query);
};

const searchGames = debounce((query: string) => {
  router.get(
    route(route().current(), route().params),
    { search: gameName.value },
    { only: ["gameList"], preserveState: true }
  );
}, 300);

// Define the props interface
interface Props {
  form: InertiaForm<GameCategoryForm>;
  submit: () => void; // Correct function signature for submit
  cmsPageOptions: Array<{ value: string | number; label: string }>;
  gameList: Array<{ value: string | number; label: string }>;
}

// Define props using defineProps in the <script setup>
const props = defineProps<Props>();
</script>



As you can see, the query data will not change in any way.

**Comment by cengizbarul** [comment]
If you add “@search-change=”($event) => $emit('search-change', $event)” in MultiSelect.vue <Multiselect, the problem will be fixed, unfortunately I always have to add it again when I update it.

**Comment by strstensky** [comment]
You can pass the searchChange function as a prop, like this:
```
:searchChange="(query) => searchChange(query)"
```
The function is triggered when typing into the search input.

**Comment by cengizbarul** [comment]
Yes, worked thank you.
