### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by PiekarskiKarol** [BRACKETS-by-TRIAD/craftable-pro-docs#15]
Hi! 
When can you expect a storybook?

**Comment by timoransky** [comment]
Hi @PiekarskiKarol,

I appreciate your interest. I was working on it today, so I can say it is close to release, but there is still some work left to be done. I believe you can expect the storybook for the most used components to be ready in the next few weeks and we will update it afterward with the rest of the components.

**Comment by PiekarskiKarol** [comment]
Hi @timoransky, 

I can't wait. BTW. I tested yesterday great job!

**Comment by strstensky** [comment]
Hi @PiekarskiKarol,
Storybook is now available at https://components.craftable.pro/
