### ISSUE TITLE
How to properly set translations for laravel validation ?

### ISSUE THREAD

**Issue by senecolas** [BRACKETS-by-TRIAD/craftable-pro-docs#21]
## Question
I would like to define a translatable message for all laravel default validation error messages (`validation.required`, `validation.unique`, ...) without using constantly the `messages()` function of `FormRequest`.
How to make it properly and link it to the craftable translation system?

**Comment by timoransky** [comment]
Hi @senecolas!
Very good and valid question. At this moment Craftable PRO doesn't scan PHP translation files, but we actually have an open pull request with this feature, so I believe it will be included in the next release.

I will keep you updated 🤗

**Comment by timoransky** [comment]
Hi @senecolas
We implemented this feature in the new version ([1.1.7](https://docs.craftable.pro/changelog#v117---2023-04-13)). All PHP lang files will be now loaded into their respective groups while scanning translations. We will release more in-depth documentation for this feature later, but everything should work out of the box 🤞
