### ISSUE TITLE
Can't edit an admin user without change his password 

### ISSUE THREAD

**Issue by senecolas** [BRACKETS-by-TRIAD/craftable-pro-docs#24]
## Issue
When I want to change a profile data of an admin user, I have to put a new password (`validation.min.string` error).
Thus, I can't change his name or his role without resetting his access...

<img width="938" alt="image" src="https://user-images.githubusercontent.com/35195832/230905877-7aa90777-79b7-45e2-a20c-8e2a3e20740c.png">

Thanks again for your great tool, and sorry about the many tiny issues ;)

**Comment by timoransky** [comment]
Hi @senecolas 
We just released a new version ([1.1.7](https://docs.craftable.pro/changelog#v117---2023-04-13)) where this bug is fixed.

**Comment by senecolas** [comment]
Hi @palypster and @timoransky,
Thank you very much for your reactivity, you are awesome !
Have a nice day
