### ISSUE TITLE
Feedback for “Users”

### ISSUE THREAD

**Issue by cmwik** [BRACKETS-by-TRIAD/craftable-pro-docs#25]
Hi,

In the docs it says "Craftable PRO comes with CRUD for users where you can manage who has the access to the Craftable PRO interface. Optionally, you can manage also other types of users for example in your frontend or mobile app (and assign them a different roles like Visitor or Member)." -- but offers no further details as to how to do that.

I'd like to be able to create models with relation to the user table and I'm wondering what is the best approach. When running `php artisan craftable-pro:generate-crud ...` in wizard mode I don't see any Craftable PRO user model to reference, only the default Laravel User, which doesn't contain any users.

What would be the best approach here?

**Comment by palypster** [comment]
We have this already on the pull request, waiting for review and being merged after that. It will be released in a few days.

Until then, one thing you can try is to choose `custom` when adding new relation in the wizard and then use `\Brackets\CraftablePro\CraftablePruUser`, but I must admin I havn't test it.

**Comment by cmwik** [comment]
Thank you so much @palypster, very helpful.

For my database migration I created the foreign key with: `$table->foreignId('craftable_pro_user_id')->constrained('craftable_pro_users')->restrictOnDelete()->casecadeOnUpdate();`

First thing to figure out was a typo in your reply (`CraftablePruUser` -> `CraftableProUser`)

After that I got an error on the generated index page which took a bit of debugging.

In the generated model and controller files:
Change `use App\Models\\Brackets\CraftablePro\CraftableProUser;` to `use Brackets\CraftablePro\Models\CraftableProUser;`
And change `->with('\Brackets\CraftablePro\CraftableProUser')` to `->with('CraftableProUser')`

In the generated Index.vue I had to change:
`{{ item.\_brackets\_craftable_pro\_craftable_pro_user.email }}` -> `{{ item.craftable_pro_user.email }}`

I also set the title to just User, by default it was "\ Brackets\ Craftable Pro\ Craftable Pro User" which didn't look so great.

Now my index page works, and the email address of the user who generated the record is displayed! Still need to fix edit form etc but should be able to figure it out. Thanks again for the support.

**Comment by palypster** [comment]
You're welcome, I'm glad I clould help. In the coming release we are going to provide to choose also internal models in the generator wizard when adding relation, so there will be no need to fix those little things manually.
