### ISSUE TITLE
Translatable fields - validation messages do not appear

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#30]
Hi!

validation messages do not appear because vue input elements have the wrong names.

Current: (generated by CRUD Generator)
```
<TextInput
    v-model="form.title[currentLocale]"
    name="title"
    :label="getLabelWithLocale($t('craftable-pro', 'Title'))"
  />
```

Expected:
```
<TextInput
    v-model="form.title[currentLocale]"
    :name="'title.' + currentLocale"
    :label="getLabelWithLocale($t('craftable-pro', 'Title'))"
  />
```

Proposal:
In the file `FormCrudGenratorHelperTrait.php` edit functions `textInput`, `wysiwigInput`, `textAreaInput` :
```
private function textInput(string $columnName, bool $isTranslatable): string
    {
        ...
        $type = $columnName === 'password' ? 'type="password"' : '';
        
       $name = $isTranslatable ?
            ":name=\"'" . $columnName . ".' + currentLocale\"" :
            "name=\"$columnName\"";

        return "
            <TextInput
                v-model=\"form.$vModel\"
                $name
                $label
                $type
            />";
    }
```

**Comment by timoransky** [comment]
Hi @Felda01 ,

this was fixed in the latest release [v1.1.15](https://docs.craftable.pro/changelog#v1115---2023-07-24). However, since we do not generate validation rules for translatable fields, you will see this change only after implementing them yourself. Let us know if you need help with that 🤗
