### ISSUE TITLE
Bug in PhpArrayScanner

### ISSUE THREAD

**Issue by Matte478** [BRACKETS-by-TRIAD/craftable-pro-docs#38]
Hi!

PhpArrayScanner overrides translations that have already been edited via the admin interface.

The issue is in the `createLanguageLineIfDoesntExist()` method of `Brackets\CraftablePro\Translations\Repositories\LanguageLineRepository`. It only checks if the translation line exists, but not which specific languages it contains.

## Proposed solution
What works for me is swapping the order of the parameters of the `array_merge()` function in the `createLanguageLineIfDoesntExist()` method - `$languageLine->text = array_merge([$language => $text], $languageLine->text)`.
If there is a translation of the given string in the DB, the values from DB will override the values from the scanned lang files.

**Comment by timoransky** [comment]
Hi @Matte478 

this issue was also fixed in the latest release 🤗
