### ISSUE TITLE
Support translation scanning for multiline strings

### ISSUE THREAD

**Issue by odziomkova-brackets** [BRACKETS-by-TRIAD/craftable-pro-docs#42]
Pri skenovaní prekladov mi toto nechcelo správne zoskenovať:
```
@lang(
    "If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\n".
    'into your web browser:',
    [
        'actionText' => $actionText,
    ]
)
```
ale toto už hej:
```
@lang('If you're having trouble clicking the ":actionText" button, copy and paste the URL below\n into your web browser:', ['actionText' => $actionText])
```
(Ten apostrof v druhom stringu bol iný ako úvodzovka na začiatku stringu, len mi ho inak skopírovalo)
Neviem či je to niečo čo stojí za to pozrieť, príp. upraviť.

**Comment by palypster** [comment]
Thank you!

I agree that it is a bug. But with low impact becuause:
1. it's super edge case to write translations like this
2. it's easy to fix it - just use more straightforward way and it'll work

So, I will close this for now as not worth solving.
