### ISSUE TITLE
Laravel-tags is installed including a migration but not used

### ISSUE THREAD

**Issue by marzsman** [BRACKETS-by-TRIAD/craftable-pro-docs#43]
Hi, 
I was about to install Laravel Tags in my project but then I noticed it is already installed in Craftable Pro, including the database migrations.
I also found a method, but it is in comment, in the CRUD generator.

Is there a (breaking) reason why it is in comment? Because I could really use it :) 
And I guess I can use the same tables for my own tags, or will there be conflicts once this is implemented in the CRUD generator?
Lastly, is a tag manager in the admin on the roadmap? That would be a nice addition ;)

**Comment by timoransky** [comment]
Hi,

initially, we planned to include Laravel Tags as a build-in feature (something like publishable), but we were experiencing some bugs in the generator and decided to finish this feature later. Of course, you can use the `tags` database table if you want to, you can even build the CRUD for tags using our generator. But for now, you have to add the tags relationship to your models manually. We hope we will find the time to finish this in the near future, but there are some other more important tasks to solve first.

**Comment by marzsman** [comment]
Ok great, was easy to integrate in my Model as everything was already installed.
Using the CRUD generator for the tags was a great suggestion. It only took my 5mins!
