### ISSUE TITLE
Settings -> Default route - production

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#51]
Hi,

On a production server, the Default Route in Settings has no options to choose from.

![image](https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/assets/15653567/303acd43-bbff-4ecc-8e8c-2c0eae3a3e54)

In `SettingsController@index` filter probably removes all routes because of condition `$route->action['prefix'] === '/admin'` (without '/' this function returns the right routes - tested in artisan tinker)

Thanks

**Comment by VladyslavMazurets** [comment]
Resolved in PR: #Fix/Default-Route

**Comment by VladyslavMazurets** [comment]
This was fixed in v1.1.21
