### ISSUE TITLE
Command artisan view:cache - error

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#52]
Hi,

command `php artisan view:cache` returns error: `The "/var/www/___path____/releases/17/vendor/brackets/craftable-pro/src/../resources/views/console" directory does not exist.`

 `CraftableProServiceProvider@configurePackage`  - `$this->loadViewsFrom(__DIR__ . '/../resources/views/console', 'brackets/craftable-pro/console');`

Thanks

**Comment by VladyslavMazurets** [comment]
Resolved in PR: [Fix/view-cache-error](https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/issues/52)

**Comment by VladyslavMazurets** [comment]
This was fixed in v1.1.21
