### ISSUE TITLE
MariaDB changes jsonb to longtext so the getAndSetTranslatableColumns is not working

### ISSUE THREAD

**Issue by blazodragan** [BRACKETS-by-TRIAD/craftable-pro-docs#56]
MariaDB changes jsonb to longtext so the getAndSetTranslatableColumns is not working because it's searching for json or jsonb - this is not a bug but if someone has a problem with setting translation when using the CRUD generator this is the reason.

A small fix for this is in line 108 WizardGeneratorTrait.php just change
->whereIn('type', ['json', 'jsonb']) to
->whereIn('type', ['json', 'jsonb', 'longtext'])

**Comment by blazodragan** [comment]
A small fix for this is in line 108 WizardGeneratorTrait.php just change 
->whereIn('type', ['json', 'jsonb']) to 
->whereIn('type', ['json', 'jsonb','longtext'])

**Comment by VladyslavMazurets** [comment]
This is in progress in the PR: [fix/type-in-wizard-generator-trait](https://github.com/BRACKETS-by-TRIAD/craftable-pro/pull/341)
