### ISSUE TITLE
Media detail preview cannot be closed

### ISSUE THREAD

**Issue by erikgreasy** [BRACKETS-by-TRIAD/craftable-pro-docs#59]
When you click and open media detail in media-library, you cannot close the sidebar(with media details), only by navigating to other media section. Adding the ability to close the sidebar/media details would be a nice thing to have.

Potential solutions which all are pretty common in other tools and CMS systems:
- add close button to the sidebar/media preview
- close the sidebar by clicking ESC
- click the selected (and highlighted) media in the grid to close the sidebar

**Comment by strstensky** [comment]
This issue was resolved in the release v2.0.0: https://docs.craftable.pro/changelog#v200---2024-02-12
