### ISSUE TITLE
Craftable Pro - Auto generated CRUD create a model with wrong paths when using a belongsTo relation

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable-pro-docs#62]
When you use the option -w to use wizard and select create a belongsTo relation the model paths generated has wrong paths to the models!

this code below is an auto-generated model with a  belongsTo relation, the CRUD generates a wrong path to the models as below!

‘‘‘
    public function category(): BelongsTo
    {
        return $this->belongsTo(App\Models\Country::class, 'country_id', 'id'); //wrong path
    }
‘‘‘

path wrong manually fixed to:

‘‘‘
    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class, 'country_id', 'id'); // App\Models\ path deleted here because it is already declared as namespace App\Models; in the beginning lines of the model file.

    }
‘‘‘

After manually changed now the path is correct and can access the model and see the view index after a new record added!
Please fix this! :)
Thanks

**Comment by strstensky** [comment]
The fix was released in version 1.1.22.

**Comment by rapgithub** [comment]
I have the latest version! very strange!
