### ISSUE TITLE
Craftable Pro - Any sample to use belongsToMany relations and pivot tables?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable-pro-docs#63]
Is it be possible for the Craftable team to make a sample code explaining how to use belongsToMany relation with Craftable Pro I tried many times to make this work and sadly it is not working on my side maybe the pivot needs specific table creation or??

I found this sample here but it only show a belongsTo relation:

https://blog.meetbrackets.com/building-laravel-9-admin-panel-with-craftable-pro-f4d7a60594db

Any update or information will be greatly appreciated!
thanks

**Comment by strstensky** [comment]
Hello,
you need to create pivot table migration. For example when you have tables pets and doctors and want to create BelongsToMany relationship between them, you should have migration `create_doctor_pet_table.php` with content
```
Schema::create('doctor_pet', function (Blueprint $table) {
            $table->foreignId('doctor_id')->constrained()->onDelete('cascade');
            $table->foreignId('pet_id')->constrained()->onDelete('cascade');
        });
```
Then you can use one of the available methods for code generation. I am attaching the output using wizard:
```
What is the type of the relation? [belongsTo]
  belongsTo ...................................................................................................................................... 0  
  belongsToMany .................................................................................................................................. 1  
❯ belongsToMany

  What is the name of the related model?
  Doctor ......................................................................................................................... App\Models\Doctor  
  Pet ............................................................................................................................... App\Models\Pet  
  CraftableProUser ................................................................................... Brackets\CraftablePro\Models\CraftableProUser  
  custom ......................................................................................................................... \Custom\Namespace  
❯ Doctor

  What is the name of the pivot table? [doctor_pet]
❯ doctor_pet

  What is the foreign pivot key in 'doctor_pet' table? [pet_id]
❯ pet_id

  What is the related pivot key in 'doctor_pet' table? [doctor_id]
❯ doctor_id

....

CRUD for model 'Pet' was generated successfully!
```

Samuel.

**Comment by palypster** [comment]
@rapgithub I hope it helped. We would be super thankful if you could let us know what we could improve (either in our docs or in the generator or in Craftable PRO itself) so this will be more clear for developers. Thank you.
