### ISSUE TITLE
Auth - Forgot password - not working

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#65]
Hi!

The forgot password link does not appear on the login page. The problem is in `AuthenticatedSessionController` -> `Route::has('craftable-pro.password.request')` - there is no route named 'password.request' only 'craftable-pro.password.request'.

The forgot password page displays the error if the email does not exist in the system. Is it safe to find out which email exists and which doesn't exist in the system?

After entering the correct email, I get an error: `Route [password.reset] is not defined.` There is only route 'craftable-pro.password.reset'.

Can you please check the functionality of the forgot password and password reset?

Thanks,

**Comment by strstensky** [comment]
Hi, this issue is resolved in the new release, feel free to update your Craftable PRO: https://docs.craftable.pro/getting-started/upgrade-guide
