### ISSUE TITLE
Craftable Pro - is it possible for CRUD to create a time field instead of datetime? 

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable-pro-docs#67]
I want to know if Craftable can handle time fields and generate the CRUD for it too.
I have a table where the orders has a fixed time to be collected everyday and the store needs to input the starting time without date for every day in the week! In this scheme below it is the start up time for Sunday day!

TABLE SCHEME

‘‘‘
            $table->time('sun_start_time_01')->nullable();
            $table->time('sun_end_time_01')->nullable();

‘‘‘

I run the CRUD generator but the time field was read as a string column! is there a way to use timestamp scheme and use only the time to be saved to  the db? or any solutions for time fields?

thanks!

Also I will like to know if I run the CRUD generator command again after I created all files, the CRUD generator auto replace the old files or I need to use some other command for it?

thanks again!

**Comment by strstensky** [comment]
Hello,

We currently do not support time fields, but we will consider adding this feature. For now, you need to manually change the generated field.

Regarding auto-replace, yes, the generator will automatically replace the files when called again.

Samuel.

**Comment by rapgithub** [comment]
Sadly I try to use the v-calendar as I see it is in the package.json installed but it seems all configs are not working at all!

https://v2.vcalendar.io/datepicker.html


```
                            mode="time" // this works
                            valid-hours="{ min: 6, max: 24 }" // does not work
                            minute-increment="5" // does not work
                            :model-config="modelConfig" // does not work
                            hide-time-header //this works
```


my code:


```
                        <DatePicker
                            v-model="form.sun_pickup_start_time_01"
                            name="sun_pickup_start_time_01"
                            mode="time"
                            valid-hours="{ min: 6, max: 24 }"
                            minute-increment="5" 
                            :model-config="modelConfig"
                            hide-time-header
                            :label="$t('craftable-pro', 'Sun Pickup Start Time 01')"
                            locale="en"
                            is24hr
                            color="black"
                            :popover="{ visibility: 'focus' }"
                        >
```


Any clues why all config are not working? if I use the module outside Craftable it works all configs but not inside Craftable... 

anything missing?

**Comment by rapgithub** [comment]
also I tried to update to the latest version available but it seems not be working because of vue 

https://github.com/nathanreyes/v-calendar


```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.3.10
npm ERR! node_modules/vue
npm ERR!   dev vue@"^3.2.31" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5.18" from v-calendar@2.4.2
npm ERR! node_modules/v-calendar
npm ERR!   dev v-calendar@"2.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by strstensky** [comment]
Hello,

We have implemented a time field into the generator. All you need to do is define columns as time in your migration. 

Regarding your problem with DatePicker props, we are using our own DatePicker component, which utilizes the V-calendar DatePicker under the hood. However, our DatePicker does not work with the same props as the V-calendar DatePicker. You can freely use the V-calendar DatePicker directly; just make sure you are importing the correct component. Your import should look like this:
```
import { DatePicker } from "v-calendar";
```
instead of this:
```
import { DatePicker } from "craftable-pro/Components";
```

Samuel.
