### ISSUE TITLE
Auth - InviteUserStoreRequest - password rules

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#68]
Hi!

can you please change the password rules in the file `InviteUserStoreRequest` to `['required', 'confirmed', Password::defaults()]` as in RegisterUserRequest?

It would be great to use `Password::defaults()` for all passwords.

Thanks,

**Comment by strstensky** [comment]
Hi, this issue is resolved in the new release, feel free to update your Craftable PRO: https://docs.craftable.pro/getting-started/upgrade-guide
