### ISSUE TITLE
Command artisan view:cache - error - v2

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#85]
Hi,

command `php artisan view:cache` returns error: ` The "____path____/vendor/brackets/craftable-pro/src/../resources/views/auth/" directory does not exist.`

`CraftableProServiceProvider@configurePackage` - `$this->loadViewsFrom(__DIR__ . '/../resources/views/auth/', 'brackets/craftable-pro/auth');`

Similar issue: https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/issues/52

Thanks

**Comment by strstensky** [comment]
Duplicate of #52 - solved in version v1.1.21.
