### ISSUE TITLE
unable to install craftabble pro

### ISSUE THREAD

**Issue by AhmadRaza1998** [BRACKETS-by-TRIAD/craftable-pro-docs#96]
Problem 1
    - Root composer.json requires brackets/craftable-pro 2.0.0 -> satisfiable by brackets/craftable-pro[v2.0.0].
    - brackets/craftable-pro v2.0.0 requires illuminate/contracts ^9.21|^10.0 -> found illuminate/contracts[v9.21.0, ..., v9.52.16, v10.0.0, ..., v10.48.18] but these were not loaded, likely because it conflicts with another require.

**Comment by strstensky** [comment]
Hi, can you paste your composer.json file here? I wasn't able to reproduce your issue with a clean Laravel 10 and Craftable PRO installation. Thanks.

**Comment by strstensky** [comment]
Since there has been no response, I am closing the issue for now.
