### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by cengizbarul** [BRACKETS-by-TRIAD/craftable-pro-docs#97]
Hello, I purchased this package, but I use MongoDB as a database, but I have problems with migrations, will mongodb support come to the project?

**Comment by strstensky** [comment]
Hello, 

At the moment, we don’t support MongoDB, but you can find the list of supported databases in our documentation here: https://docs.craftable.pro/getting-started#requirements. If you're able to, I’d recommend using one of those options.
