### ISSUE TITLE
User model problem.

### ISSUE THREAD

**Issue by cengizbarul** [BRACKETS-by-TRIAD/craftable-pro-docs#99]
Greetings,

php artisan craftable-pro:generate-crud

When we run the users table with this command, the following columns were not found in available selection: 0, 1, 2, 3, 4, 5, 7, 8. gives an error and does not detect, but the table is attached in the database.

**Comment by strstensky** [comment]
Hello,
this issue should be fixed in version v2.0.4. It was caused by one of the dependencies. Feel free to update! :)

**Comment by cengizbarul** [comment]
Thanks
